-- -- CamGuard Phase 2: normalized Supabase data layer.
-- -- Stores camera-security metadata only. Never store camera images, video, audio, or captured media paths.

-- create extension if not exists pgcrypto;

-- create or replace function public.set_updated_at()
-- returns trigger
-- language plpgsql
-- as $$
-- begin
--   new.updated_at = now();
--   return new;
-- end;
-- $$;

-- create table public.users (
--   id uuid primary key references auth.users(id) on delete cascade,
--   display_name text,
--   created_at timestamptz not null default now(),
--   updated_at timestamptz not null default now()
-- );

-- create table public.device_types (
--   id smallint generated by default as identity primary key,
--   key text not null unique,
--   display_name text not null,
--   created_at timestamptz not null default now(),
--   constraint device_types_key_format check (key ~ '^[a-z0-9_]+$')
-- );

-- create table public.operating_systems (
--   id uuid primary key default gen_random_uuid(),
--   device_type_id smallint not null references public.device_types(id),
--   name text not null,
--   version text not null,
--   created_at timestamptz not null default now(),
--   unique (device_type_id, name, version)
-- );

-- create table public.devices (
--   id uuid primary key default gen_random_uuid(),
--   user_id uuid not null references public.users(id) on delete cascade,
--   device_type_id smallint not null references public.device_types(id),
--   operating_system_id uuid references public.operating_systems(id),
--   client_device_id text not null,
--   display_name text not null,
--   model_name text,
--   last_seen_at timestamptz,
--   created_at timestamptz not null default now(),
--   updated_at timestamptz not null default now(),
--   unique (user_id, client_device_id)
-- );

-- create table public.applications (
--   id uuid primary key default gen_random_uuid(),
--   device_type_id smallint references public.device_types(id),
--   display_name text not null,
--   bundle_identifier text,
--   signing_team_id text,
--   first_seen_at timestamptz not null default now(),
--   last_seen_at timestamptz,
--   created_at timestamptz not null default now(),
--   updated_at timestamptz not null default now()
-- );

-- create unique index applications_known_bundle_unique
--   on public.applications (device_type_id, bundle_identifier)
--   where bundle_identifier is not null;

-- create table public.trusted_applications (
--   id uuid primary key default gen_random_uuid(),
--   user_id uuid not null references public.users(id) on delete cascade,
--   device_id uuid references public.devices(id) on delete cascade,
--   application_id uuid not null references public.applications(id) on delete cascade,
--   is_trusted boolean not null default true,
--   trusted_reason text,
--   created_at timestamptz not null default now(),
--   updated_at timestamptz not null default now(),
--   unique (user_id, device_id, application_id)
-- );

-- create table public.permission_statuses (
--   id smallint generated by default as identity primary key,
--   key text not null unique,
--   display_name text not null,
--   created_at timestamptz not null default now(),
--   constraint permission_statuses_key_format check (key ~ '^[a-z0-9_]+$')
-- );

-- create table public.event_types (
--   id smallint generated by default as identity primary key,
--   key text not null unique,
--   display_name text not null,
--   created_at timestamptz not null default now(),
--   constraint event_types_key_format check (key ~ '^[a-z0-9_]+$')
-- );

-- create table public.threat_levels (
--   id smallint generated by default as identity primary key,
--   key text not null unique,
--   display_name text not null,
--   minimum_probability numeric(5,4) not null,
--   maximum_probability numeric(5,4) not null,
--   maximum_inclusive boolean not null default false,
--   alert_required boolean not null default false,
--   dashboard_status_token text not null,
--   created_at timestamptz not null default now(),
--   constraint threat_levels_key_format check (key ~ '^[a-z0-9_]+$'),
--   constraint threat_levels_probability_range check (
--     minimum_probability >= 0
--     and maximum_probability <= 1
--     and minimum_probability < maximum_probability
--   )
-- );

-- create table public.tcb_feature_metrics (
--   id smallint generated by default as identity primary key,
--   key text not null unique,
--   display_name text not null,
--   unit text not null,
--   used_in_covariance boolean not null default false,
--   created_at timestamptz not null default now(),
--   constraint tcb_feature_metrics_key_format check (key ~ '^[a-z0-9_]+$')
-- );

-- create table public.camera_events (
--   id uuid primary key default gen_random_uuid(),
--   user_id uuid not null references public.users(id) on delete cascade,
--   device_id uuid not null references public.devices(id) on delete cascade,
--   application_id uuid references public.applications(id),
--   event_type_id smallint not null references public.event_types(id),
--   permission_status_id smallint references public.permission_statuses(id),
--   client_event_id uuid not null,
--   session_id uuid,
--   occurred_at timestamptz not null,
--   collected_at timestamptz not null,
--   camera_status text not null,
--   duration_seconds numeric(12,3),
--   activation_count_recent_window integer not null default 0,
--   recent_window_seconds integer not null default 600,
--   is_background_access boolean not null default false,
--   is_repeated_short_activation boolean not null default false,
--   is_unknown_application boolean not null default false,
--   is_untrusted_application boolean not null default false,
--   permission_changed_recently boolean not null default false,
--   network_upload_after_camera boolean not null default false,
--   network_window_seconds integer not null default 30,
--   is_simulated boolean not null default false,
--   simulation_label text,
--   notes text,
--   created_at timestamptz not null default now(),
--   constraint camera_events_duration_nonnegative check (duration_seconds is null or duration_seconds >= 0),
--   constraint camera_events_recent_window_positive check (recent_window_seconds > 0),
--   constraint camera_events_network_window_positive check (network_window_seconds > 0),
--   constraint camera_events_simulation_label_required check (
--     is_simulated = false or nullif(trim(simulation_label), '') is not null
--   ),
--   unique (device_id, client_event_id)
-- );

-- create table public.network_endpoints (
--   id uuid primary key default gen_random_uuid(),
--   user_id uuid not null references public.users(id) on delete cascade,
--   destination_ip inet,
--   destination_hostname text,
--   destination_port integer,
--   protocol text not null default 'unknown',
--   asn integer,
--   organization text,
--   country_code char(2),
--   region text,
--   city text,
--   latitude numeric(9,6),
--   longitude numeric(9,6),
--   is_vpn_or_proxy boolean,
--   is_tor_exit_node boolean,
--   first_seen_at timestamptz not null default now(),
--   last_seen_at timestamptz,
--   created_at timestamptz not null default now(),
--   updated_at timestamptz not null default now(),
--   constraint network_endpoints_has_destination check (
--     destination_ip is not null or nullif(trim(destination_hostname), '') is not null
--   ),
--   constraint network_endpoints_port_range check (destination_port is null or destination_port between 1 and 65535),
--   constraint network_endpoints_protocol_check check (protocol in ('tcp', 'udp', 'quic', 'icmp', 'unknown')),
--   constraint network_endpoints_asn_positive check (asn is null or asn > 0),
--   constraint network_endpoints_country_code_format check (country_code is null or country_code ~ '^[A-Z]{2}$'),
--   constraint network_endpoints_latitude_range check (latitude is null or latitude between -90 and 90),
--   constraint network_endpoints_longitude_range check (longitude is null or longitude between -180 and 180),
--   unique (user_id, destination_ip, destination_hostname, destination_port, protocol)
-- );

-- create table public.network_reputation_sources (
--   id smallint generated by default as identity primary key,
--   key text not null unique,
--   display_name text not null,
--   created_at timestamptz not null default now(),
--   constraint network_reputation_sources_key_format check (key ~ '^[a-z0-9_]+$')
-- );

-- create table public.network_endpoint_reputations (
--   id uuid primary key default gen_random_uuid(),
--   user_id uuid not null references public.users(id) on delete cascade,
--   network_endpoint_id uuid not null references public.network_endpoints(id) on delete cascade,
--   reputation_source_id smallint not null references public.network_reputation_sources(id),
--   reputation_score numeric(6,4),
--   risk_label text,
--   is_malicious boolean,
--   checked_at timestamptz not null default now(),
--   created_at timestamptz not null default now(),
--   updated_at timestamptz not null default now(),
--   constraint network_endpoint_reputations_score_range check (
--     reputation_score is null or reputation_score between 0 and 1
--   ),
--   unique (network_endpoint_id, reputation_source_id)
-- );

-- create table public.network_events (
--   id uuid primary key default gen_random_uuid(),
--   user_id uuid not null references public.users(id) on delete cascade,
--   device_id uuid not null references public.devices(id) on delete cascade,
--   application_id uuid references public.applications(id),
--   camera_event_id uuid references public.camera_events(id) on delete set null,
--   network_endpoint_id uuid references public.network_endpoints(id) on delete set null,
--   occurred_at timestamptz not null,
--   direction text not null,
--   bytes_count bigint,
--   is_upload boolean not null default false,
--   is_simulated boolean not null default false,
--   created_at timestamptz not null default now(),
--   constraint network_events_direction_check check (direction in ('upload', 'download', 'bidirectional', 'unknown')),
--   constraint network_events_bytes_nonnegative check (bytes_count is null or bytes_count >= 0)
-- );

-- create table public.permission_events (
--   id uuid primary key default gen_random_uuid(),
--   user_id uuid not null references public.users(id) on delete cascade,
--   device_id uuid not null references public.devices(id) on delete cascade,
--   application_id uuid references public.applications(id),
--   event_type_id smallint not null references public.event_types(id),
--   previous_permission_status_id smallint references public.permission_statuses(id),
--   permission_status_id smallint not null references public.permission_statuses(id),
--   occurred_at timestamptz not null,
--   collected_at timestamptz not null,
--   created_at timestamptz not null default now()
-- );

-- create table public.behavior_profiles (
--   id uuid primary key default gen_random_uuid(),
--   user_id uuid not null references public.users(id) on delete cascade,
--   device_id uuid not null references public.devices(id) on delete cascade,
--   application_id uuid not null references public.applications(id) on delete cascade,
--   sample_count integer not null default 0,
--   window_days integer not null default 30,
--   last_trained_at timestamptz,
--   created_at timestamptz not null default now(),
--   updated_at timestamptz not null default now(),
--   constraint behavior_profiles_sample_count_nonnegative check (sample_count >= 0),
--   constraint behavior_profiles_window_days_positive check (window_days > 0),
--   unique (device_id, application_id)
-- );

-- create table public.behavior_profile_metrics (
--   id uuid primary key default gen_random_uuid(),
--   behavior_profile_id uuid not null references public.behavior_profiles(id) on delete cascade,
--   metric_id smallint not null references public.tcb_feature_metrics(id),
--   mean_value numeric(18,6) not null,
--   stddev_value numeric(18,6) not null,
--   created_at timestamptz not null default now(),
--   updated_at timestamptz not null default now(),
--   constraint behavior_profile_metrics_stddev_nonnegative check (stddev_value >= 0),
--   unique (behavior_profile_id, metric_id)
-- );

-- create table public.behavior_profile_covariances (
--   id uuid primary key default gen_random_uuid(),
--   behavior_profile_id uuid not null references public.behavior_profiles(id) on delete cascade,
--   metric_x_id smallint not null references public.tcb_feature_metrics(id),
--   metric_y_id smallint not null references public.tcb_feature_metrics(id),
--   covariance_value numeric(18,6) not null,
--   created_at timestamptz not null default now(),
--   updated_at timestamptz not null default now(),
--   constraint behavior_profile_covariances_order check (metric_x_id <= metric_y_id),
--   unique (behavior_profile_id, metric_x_id, metric_y_id)
-- );

-- create table public.threat_scores (
--   id uuid primary key default gen_random_uuid(),
--   user_id uuid not null references public.users(id) on delete cascade,
--   camera_event_id uuid not null unique references public.camera_events(id) on delete cascade,
--   behavior_profile_id uuid references public.behavior_profiles(id) on delete set null,
--   threat_level_id smallint not null references public.threat_levels(id),
--   anomaly_score numeric(18,6) not null,
--   contextual_score numeric(18,6) not null,
--   threat_probability numeric(7,6) not null,
--   feature_access_time_hour numeric(8,4),
--   feature_duration_seconds numeric(12,3),
--   feature_activation_frequency integer,
--   feature_background_access boolean not null default false,
--   feature_unknown_or_untrusted boolean not null default false,
--   feature_network_upload_after_camera boolean not null default false,
--   feature_permission_changed_recently boolean not null default false,
--   feature_repeated_short_activation boolean not null default false,
--   scoring_version text not null default 'tcb-ad-1',
--   scored_at timestamptz not null default now(),
--   created_at timestamptz not null default now(),
--   constraint threat_scores_anomaly_nonnegative check (anomaly_score >= 0),
--   constraint threat_scores_contextual_nonnegative check (contextual_score >= 0),
--   constraint threat_scores_probability_range check (threat_probability between 0 and 1)
-- );

-- create table public.alerts (
--   id uuid primary key default gen_random_uuid(),
--   user_id uuid not null references public.users(id) on delete cascade,
--   device_id uuid not null references public.devices(id) on delete cascade,
--   camera_event_id uuid references public.camera_events(id) on delete cascade,
--   threat_score_id uuid references public.threat_scores(id) on delete cascade,
--   threat_level_id smallint not null references public.threat_levels(id),
--   title text not null,
--   message text not null,
--   acknowledged_at timestamptz,
--   resolved_at timestamptz,
--   created_at timestamptz not null default now()
-- );

-- create trigger users_set_updated_at
--   before update on public.users
--   for each row execute function public.set_updated_at();

-- create trigger devices_set_updated_at
--   before update on public.devices
--   for each row execute function public.set_updated_at();

-- create trigger applications_set_updated_at
--   before update on public.applications
--   for each row execute function public.set_updated_at();

-- create trigger trusted_applications_set_updated_at
--   before update on public.trusted_applications
--   for each row execute function public.set_updated_at();

-- create trigger network_endpoints_set_updated_at
--   before update on public.network_endpoints
--   for each row execute function public.set_updated_at();

-- create trigger network_endpoint_reputations_set_updated_at
--   before update on public.network_endpoint_reputations
--   for each row execute function public.set_updated_at();

-- create trigger behavior_profiles_set_updated_at
--   before update on public.behavior_profiles
--   for each row execute function public.set_updated_at();

-- create trigger behavior_profile_metrics_set_updated_at
--   before update on public.behavior_profile_metrics
--   for each row execute function public.set_updated_at();

-- create trigger behavior_profile_covariances_set_updated_at
--   before update on public.behavior_profile_covariances
--   for each row execute function public.set_updated_at();

-- create index devices_user_id_idx on public.devices (user_id);
-- create index devices_last_seen_at_idx on public.devices (last_seen_at desc);
-- create index applications_display_name_idx on public.applications (display_name);
-- create index trusted_applications_user_device_idx on public.trusted_applications (user_id, device_id);
-- create index camera_events_user_occurred_idx on public.camera_events (user_id, occurred_at desc);
-- create index camera_events_device_occurred_idx on public.camera_events (device_id, occurred_at desc);
-- create index camera_events_application_idx on public.camera_events (application_id);
-- create index camera_events_network_correlation_idx on public.camera_events (device_id, occurred_at, network_upload_after_camera);
-- create index network_endpoints_user_seen_idx on public.network_endpoints (user_id, last_seen_at desc);
-- create index network_endpoints_ip_idx on public.network_endpoints (destination_ip);
-- create index network_endpoints_hostname_idx on public.network_endpoints (destination_hostname);
-- create index network_endpoints_location_idx on public.network_endpoints (country_code, region, city);
-- create index network_endpoint_reputations_endpoint_idx on public.network_endpoint_reputations (network_endpoint_id, checked_at desc);
-- create index network_events_device_occurred_idx on public.network_events (device_id, occurred_at desc);
-- create index network_events_camera_event_idx on public.network_events (camera_event_id);
-- create index network_events_endpoint_idx on public.network_events (network_endpoint_id);
-- create index permission_events_device_occurred_idx on public.permission_events (device_id, occurred_at desc);
-- create index behavior_profiles_user_device_idx on public.behavior_profiles (user_id, device_id);
-- create index threat_scores_user_scored_idx on public.threat_scores (user_id, scored_at desc);
-- create index threat_scores_level_idx on public.threat_scores (threat_level_id, scored_at desc);
-- create index alerts_user_created_idx on public.alerts (user_id, created_at desc);
-- create index alerts_device_created_idx on public.alerts (device_id, created_at desc);
-- create index alerts_unresolved_idx on public.alerts (user_id, created_at desc) where resolved_at is null;

-- insert into public.device_types (key, display_name) values
--   ('macos', 'macOS'),
--   ('ios', 'iPhone')
-- on conflict (key) do update set display_name = excluded.display_name;

-- insert into public.permission_statuses (key, display_name) values
--   ('authorized', 'Authorized'),
--   ('denied', 'Denied'),
--   ('restricted', 'Restricted'),
--   ('not_determined', 'Not Determined'),
--   ('unknown', 'Unknown')
-- on conflict (key) do update set display_name = excluded.display_name;

-- insert into public.event_types (key, display_name) values
--   ('camera_session', 'Camera Session'),
--   ('permission_change', 'Permission Change'),
--   ('network_activity', 'Network Activity'),
--   ('simulation', 'Simulation')
-- on conflict (key) do update set display_name = excluded.display_name;

-- insert into public.threat_levels (
--   key,
--   display_name,
--   minimum_probability,
--   maximum_probability,
--   maximum_inclusive,
--   alert_required,
--   dashboard_status_token
-- ) values
--   ('normal', 'Normal', 0.0000, 0.5000, false, false, 'status.normal'),
--   ('suspicious', 'Suspicious', 0.5000, 0.8500, false, true, 'status.suspicious'),
--   ('critical', 'Critical', 0.8500, 1.0000, true, true, 'status.critical')
-- on conflict (key) do update set
--   display_name = excluded.display_name,
--   minimum_probability = excluded.minimum_probability,
--   maximum_probability = excluded.maximum_probability,
--   maximum_inclusive = excluded.maximum_inclusive,
--   alert_required = excluded.alert_required,
--   dashboard_status_token = excluded.dashboard_status_token;

-- insert into public.tcb_feature_metrics (key, display_name, unit, used_in_covariance) values
--   ('access_time_hour', 'Access Time Hour', 'hour_of_day', true),
--   ('duration_seconds', 'Duration Seconds', 'seconds', true),
--   ('activation_frequency', 'Activation Frequency', 'count_per_window', true),
--   ('network_upload_count', 'Network Upload Count', 'count_per_window', true),
--   ('background_access', 'Background Access', 'boolean', false),
--   ('unknown_or_untrusted', 'Unknown or Untrusted Application', 'boolean', false),
--   ('permission_changed_recently', 'Permission Changed Recently', 'boolean', false),
--   ('repeated_short_activation', 'Repeated Short Activation', 'boolean', false)
-- on conflict (key) do update set
--   display_name = excluded.display_name,
--   unit = excluded.unit,
--   used_in_covariance = excluded.used_in_covariance;

-- insert into public.network_reputation_sources (key, display_name) values
--   ('internal_observation', 'Internal Observation'),
--   ('manual_review', 'Manual Review'),
--   ('external_reputation', 'External Reputation')
-- on conflict (key) do update set display_name = excluded.display_name;

-- alter table public.users enable row level security;
-- alter table public.device_types enable row level security;
-- alter table public.operating_systems enable row level security;
-- alter table public.devices enable row level security;
-- alter table public.applications enable row level security;
-- alter table public.trusted_applications enable row level security;
-- alter table public.permission_statuses enable row level security;
-- alter table public.event_types enable row level security;
-- alter table public.threat_levels enable row level security;
-- alter table public.tcb_feature_metrics enable row level security;
-- alter table public.camera_events enable row level security;
-- alter table public.network_endpoints enable row level security;
-- alter table public.network_reputation_sources enable row level security;
-- alter table public.network_endpoint_reputations enable row level security;
-- alter table public.network_events enable row level security;
-- alter table public.permission_events enable row level security;
-- alter table public.behavior_profiles enable row level security;
-- alter table public.behavior_profile_metrics enable row level security;
-- alter table public.behavior_profile_covariances enable row level security;
-- alter table public.threat_scores enable row level security;
-- alter table public.alerts enable row level security;

-- create policy users_select_own on public.users
--   for select using (auth.uid() = id);

-- create policy users_insert_own on public.users
--   for insert with check (auth.uid() = id);

-- create policy users_update_own on public.users
--   for update using (auth.uid() = id) with check (auth.uid() = id);

-- create policy device_types_read_authenticated on public.device_types
--   for select to authenticated using (true);

-- create policy operating_systems_read_authenticated on public.operating_systems
--   for select to authenticated using (true);

-- create policy permission_statuses_read_authenticated on public.permission_statuses
--   for select to authenticated using (true);

-- create policy event_types_read_authenticated on public.event_types
--   for select to authenticated using (true);

-- create policy threat_levels_read_authenticated on public.threat_levels
--   for select to authenticated using (true);

-- create policy tcb_feature_metrics_read_authenticated on public.tcb_feature_metrics
--   for select to authenticated using (true);

-- create policy network_reputation_sources_read_authenticated on public.network_reputation_sources
--   for select to authenticated using (true);

-- create policy devices_select_own on public.devices
--   for select using (auth.uid() = user_id);

-- create policy devices_insert_own on public.devices
--   for insert with check (auth.uid() = user_id);

-- create policy devices_update_own on public.devices
--   for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- create policy applications_read_authenticated on public.applications
--   for select to authenticated using (true);

-- create policy trusted_applications_select_own on public.trusted_applications
--   for select using (auth.uid() = user_id);

-- create policy trusted_applications_insert_own on public.trusted_applications
--   for insert with check (auth.uid() = user_id);

-- create policy trusted_applications_update_own on public.trusted_applications
--   for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- create policy camera_events_select_own on public.camera_events
--   for select using (auth.uid() = user_id);

-- create policy network_endpoints_select_own on public.network_endpoints
--   for select using (auth.uid() = user_id);

-- create policy network_endpoint_reputations_select_own on public.network_endpoint_reputations
--   for select using (auth.uid() = user_id);

-- create policy network_events_select_own on public.network_events
--   for select using (auth.uid() = user_id);

-- create policy permission_events_select_own on public.permission_events
--   for select using (auth.uid() = user_id);

-- create policy behavior_profiles_select_own on public.behavior_profiles
--   for select using (auth.uid() = user_id);

-- create policy behavior_profile_metrics_select_own on public.behavior_profile_metrics
--   for select using (
--     exists (
--       select 1
--       from public.behavior_profiles bp
--       where bp.id = behavior_profile_metrics.behavior_profile_id
--         and bp.user_id = auth.uid()
--     )
--   );

-- create policy behavior_profile_covariances_select_own on public.behavior_profile_covariances
--   for select using (
--     exists (
--       select 1
--       from public.behavior_profiles bp
--       where bp.id = behavior_profile_covariances.behavior_profile_id
--         and bp.user_id = auth.uid()
--     )
--   );

-- create policy threat_scores_select_own on public.threat_scores
--   for select using (auth.uid() = user_id);

-- create policy alerts_select_own on public.alerts
--   for select using (auth.uid() = user_id);

-- create policy alerts_update_own on public.alerts
--   for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
